// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "8434cc33-cee1-49d9-a098-dfa7f37aed9e");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1700162794);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1700162786);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{7b4e35bc-8546-48dd-98eb-052c18ee5a36}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1700162771);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 139);
user_pref("browser.newtabpage.activity-stream.impressionId", "{57798c73-af81-4545-8801-fad8fd49287d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1700162778);
user_pref("browser.search.region", "RU");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230929164800");
user_pref("browser.startup.homepage_override.mstone", "118.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1700162776);
user_pref("browser.topsites.contile.lastFetch", 1700162780);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1700162783319");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "118.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "RU");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230929164800");
user_pref("extensions.lastAppVersion", "118.0.1");
user_pref("extensions.lastPlatformVersion", "118.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3594eb16-f61e-4061-b88c-482e52368849\",\"pictureinpicture@mozilla.org\":\"f5f31b52-f4e4-4461-b9b3-12051f5d4d18\",\"screenshots@mozilla.org\":\"6dd919c9-c34d-4615-aabf-c27c2227038b\",\"webcompat-reporter@mozilla.org\":\"7cdf768f-4cff-42fe-8bfa-23318594a9f3\",\"webcompat@mozilla.org\":\"8cf1f265-18c5-4655-8cfc-4eee5e28ad84\",\"default-theme@mozilla.org\":\"45715cae-135b-4eca-bcc8-73fb57a6afd2\",\"addons-search-detection@mozilla.com\":\"a9f7d16e-c8c4-469b-888d-62857b6e8600\",\"google@search.mozilla.org\":\"b286e677-952e-4073-b61b-805e54c59016\",\"amazondotcom@search.mozilla.org\":\"488f5821-93c6-403c-be74-ad5e28a639c7\",\"wikipedia@search.mozilla.org\":\"072d7943-4022-4868-b11a-31ad62739a6e\",\"bing@search.mozilla.org\":\"36632be8-6968-4d77-8fb9-877a60eda16a\",\"ddg@search.mozilla.org\":\"dddc90a9-cbe5-4cd1-8a51-b2579f62591e\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.pocketNewtab", "{\"slug\":\"rollout-of-share-of-voice-for-sponsored-topsites-rest-of-world\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"pocketNewtab\"},\"features\":null},\"active\":true,\"enrollmentId\":\"8dc2f409-465e-41b7-8f5d-6dab82bf2816\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Rollout of Share-of-Voice for Sponsored TopSites Rest of World\",\"userFacingDescription\":\"Rollout of the Share-of-Voice feature to dynamically manage ad inventory on the NewTab page.\",\"lastSeen\":\"2023-11-16T19:26:25.861Z\",\"featureIds\":[\"pocketNewtab\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.topSitesContileSovEnabled", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"enrollmentId\":\"3597ebc2-cadc-4ea8-9253-a538a8230bc8\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2023-11-16T19:26:26.069Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f711e6c4-6294-4789-b0aa-ec0ee104a030");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1700162762);
user_pref("toolkit.telemetry.cachedClientID", "fb9418b4-7d66-4987-a4ae-88ebd22c426d");
user_pref("toolkit.telemetry.previousBuildID", "20230929164800");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
